# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basic_calculate_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_basic_calculate(object):
    def setupUi(self, basic_calculate):
        basic_calculate.setObjectName("basic_calculate")
        basic_calculate.resize(250, 300)
        basic_calculate.setStyleSheet("")
        self.pushButton_9 = QtWidgets.QPushButton(basic_calculate)
        self.pushButton_9.setGeometry(QtCore.QRect(126, 118, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: 1px solid ;")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_7 = QtWidgets.QPushButton(basic_calculate)
        self.pushButton_7.setGeometry(QtCore.QRect(6, 118, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: 1px solid ;")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_4 = QtWidgets.QPushButton(basic_calculate)
        self.pushButton_4.setGeometry(QtCore.QRect(6, 163, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: 1px solid ;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(basic_calculate)
        self.pushButton_6.setGeometry(QtCore.QRect(126, 163, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: 1px solid ;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_eq = QtWidgets.QPushButton(basic_calculate)
        self.pushButton_eq.setGeometry(QtCore.QRect(126, 253, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_eq.setFont(font)
        self.pushButton_eq.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"border: 4px double ;")
        self.pushButton_eq.setObjectName("pushButton_eq")
        self.pushButton_3 = QtWidgets.QPushButton(basic_calculate)
        self.pushButton_3.setGeometry(QtCore.QRect(126, 208, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: 1px solid ;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_point = QtWidgets.QPushButton(basic_calculate)
        self.pushButton_point.setGeometry(QtCore.QRect(66, 253, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_point.setFont(font)
        self.pushButton_point.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: 1px solid ;")
        self.pushButton_point.setObjectName("pushButton_point")
        self.pushButton_0 = QtWidgets.QPushButton(basic_calculate)
        self.pushButton_0.setGeometry(QtCore.QRect(6, 253, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: 1px solid ;")
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_1 = QtWidgets.QPushButton(basic_calculate)
        self.pushButton_1.setGeometry(QtCore.QRect(6, 208, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: 1px solid ;")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_add = QtWidgets.QPushButton(basic_calculate)
        self.pushButton_add.setGeometry(QtCore.QRect(186, 253, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setStyleSheet("background-color: rgb(160, 180, 40);\n"
"border: 1px solid ;")
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_2 = QtWidgets.QPushButton(basic_calculate)
        self.pushButton_2.setGeometry(QtCore.QRect(66, 208, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: 1px solid ;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_5 = QtWidgets.QPushButton(basic_calculate)
        self.pushButton_5.setGeometry(QtCore.QRect(66, 163, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: 1px solid ;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_8 = QtWidgets.QPushButton(basic_calculate)
        self.pushButton_8.setGeometry(QtCore.QRect(66, 118, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: 1px solid ;")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_div = QtWidgets.QPushButton(basic_calculate)
        self.pushButton_div.setGeometry(QtCore.QRect(186, 118, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_div.setFont(font)
        self.pushButton_div.setStyleSheet("background-color: rgb(160, 180, 40);\n"
"border: 1px solid ;")
        self.pushButton_div.setObjectName("pushButton_div")
        self.pushButton_mul = QtWidgets.QPushButton(basic_calculate)
        self.pushButton_mul.setGeometry(QtCore.QRect(186, 163, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_mul.setFont(font)
        self.pushButton_mul.setStyleSheet("background-color: rgb(160, 180, 40);\n"
"border: 1px solid ;")
        self.pushButton_mul.setObjectName("pushButton_mul")
        self.pushButton_sub = QtWidgets.QPushButton(basic_calculate)
        self.pushButton_sub.setGeometry(QtCore.QRect(186, 208, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_sub.setFont(font)
        self.pushButton_sub.setStyleSheet("background-color: rgb(160, 180, 40);\n"
"border: 1px solid ;")
        self.pushButton_sub.setObjectName("pushButton_sub")
        self.pushButton_c = QtWidgets.QPushButton(basic_calculate)
        self.pushButton_c.setGeometry(QtCore.QRect(186, 70, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_c.setFont(font)
        self.pushButton_c.setStyleSheet("background-color: rgb(255, 85, 85);\n"
"border: 4px double ;")
        self.pushButton_c.setObjectName("pushButton_c")
        self.lineEdit = QtWidgets.QLineEdit(basic_calculate)
        self.lineEdit.setGeometry(QtCore.QRect(5, 14, 240, 51))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.listView = QtWidgets.QListView(basic_calculate)
        self.listView.setGeometry(QtCore.QRect(0, 0, 256, 301))
        self.listView.setStyleSheet("border-image: url(:/newPrefix/background2.jpg);")
        self.listView.setObjectName("listView")
        self.listView.raise_()
        self.pushButton_9.raise_()
        self.pushButton_7.raise_()
        self.pushButton_4.raise_()
        self.pushButton_6.raise_()
        self.pushButton_eq.raise_()
        self.pushButton_3.raise_()
        self.pushButton_point.raise_()
        self.pushButton_0.raise_()
        self.pushButton_1.raise_()
        self.pushButton_add.raise_()
        self.pushButton_2.raise_()
        self.pushButton_5.raise_()
        self.pushButton_8.raise_()
        self.pushButton_div.raise_()
        self.pushButton_mul.raise_()
        self.pushButton_sub.raise_()
        self.pushButton_c.raise_()
        self.lineEdit.raise_()

        self.retranslateUi(basic_calculate)
        QtCore.QMetaObject.connectSlotsByName(basic_calculate)

    def retranslateUi(self, basic_calculate):
        _translate = QtCore.QCoreApplication.translate
        basic_calculate.setWindowTitle(_translate("basic_calculate", "基础计算"))
        self.pushButton_9.setText(_translate("basic_calculate", "9"))
        self.pushButton_7.setText(_translate("basic_calculate", "7"))
        self.pushButton_4.setText(_translate("basic_calculate", "4"))
        self.pushButton_6.setText(_translate("basic_calculate", "6"))
        self.pushButton_eq.setText(_translate("basic_calculate", "="))
        self.pushButton_3.setText(_translate("basic_calculate", "3"))
        self.pushButton_point.setText(_translate("basic_calculate", "."))
        self.pushButton_0.setText(_translate("basic_calculate", "0"))
        self.pushButton_1.setText(_translate("basic_calculate", "1"))
        self.pushButton_add.setText(_translate("basic_calculate", "+"))
        self.pushButton_2.setText(_translate("basic_calculate", "2"))
        self.pushButton_5.setText(_translate("basic_calculate", "5"))
        self.pushButton_8.setText(_translate("basic_calculate", "8"))
        self.pushButton_div.setText(_translate("basic_calculate", "÷"))
        self.pushButton_mul.setText(_translate("basic_calculate", "×"))
        self.pushButton_sub.setText(_translate("basic_calculate", "-"))
        self.pushButton_c.setText(_translate("basic_calculate", "C"))
