# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'metric_change_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_metric_change(object):
    def setupUi(self, metric_change):
        metric_change.setObjectName("metric_change")
        metric_change.resize(450, 300)
        self.lineEdit_l1 = QtWidgets.QLineEdit(metric_change)
        self.lineEdit_l1.setGeometry(QtCore.QRect(40, 80, 100, 20))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.lineEdit_l1.setFont(font)
        self.lineEdit_l1.setText("")
        self.lineEdit_l1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_l1.setObjectName("lineEdit_l1")
        self.lineEdit_l2 = QtWidgets.QLineEdit(metric_change)
        self.lineEdit_l2.setGeometry(QtCore.QRect(260, 80, 100, 20))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.lineEdit_l2.setFont(font)
        self.lineEdit_l2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_l2.setReadOnly(True)
        self.lineEdit_l2.setObjectName("lineEdit_l2")
        self.comboBox_l1 = QtWidgets.QComboBox(metric_change)
        self.comboBox_l1.setGeometry(QtCore.QRect(140, 80, 50, 20))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(14)
        self.comboBox_l1.setFont(font)
        self.comboBox_l1.setObjectName("comboBox_l1")
        self.comboBox_l1.addItem("")
        self.comboBox_l1.addItem("")
        self.comboBox_l1.addItem("")
        self.comboBox_l1.addItem("")
        self.comboBox_l1.addItem("")
        self.comboBox_l1.addItem("")
        self.comboBox_l1.addItem("")
        self.comboBox_l1.addItem("")
        self.comboBox_l1.addItem("")
        self.comboBox_l1.addItem("")
        self.comboBox_l1.addItem("")
        self.comboBox_l1.addItem("")
        self.comboBox_l1.addItem("")
        self.label = QtWidgets.QLabel(metric_change)
        self.label.setGeometry(QtCore.QRect(0, 10, 441, 31))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_l = QtWidgets.QLabel(metric_change)
        self.label_l.setGeometry(QtCore.QRect(200, 40, 50, 20))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(14)
        self.label_l.setFont(font)
        self.label_l.setStyleSheet("")
        self.label_l.setAlignment(QtCore.Qt.AlignCenter)
        self.label_l.setObjectName("label_l")
        self.label_v = QtWidgets.QLabel(metric_change)
        self.label_v.setGeometry(QtCore.QRect(200, 120, 50, 20))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(14)
        self.label_v.setFont(font)
        self.label_v.setStyleSheet("")
        self.label_v.setAlignment(QtCore.Qt.AlignCenter)
        self.label_v.setObjectName("label_v")
        self.label_m = QtWidgets.QLabel(metric_change)
        self.label_m.setGeometry(QtCore.QRect(200, 200, 50, 20))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(14)
        self.label_m.setFont(font)
        self.label_m.setStyleSheet("")
        self.label_m.setAlignment(QtCore.Qt.AlignCenter)
        self.label_m.setObjectName("label_m")
        self.pushButton_l = QtWidgets.QPushButton(metric_change)
        self.pushButton_l.setGeometry(QtCore.QRect(200, 80, 50, 20))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(18)
        self.pushButton_l.setFont(font)
        self.pushButton_l.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: 4px double ;")
        self.pushButton_l.setObjectName("pushButton_l")
        self.pushButton_v = QtWidgets.QPushButton(metric_change)
        self.pushButton_v.setGeometry(QtCore.QRect(200, 160, 50, 20))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(18)
        self.pushButton_v.setFont(font)
        self.pushButton_v.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: 4px double ;")
        self.pushButton_v.setObjectName("pushButton_v")
        self.comboBox_v1 = QtWidgets.QComboBox(metric_change)
        self.comboBox_v1.setGeometry(QtCore.QRect(140, 160, 50, 20))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(14)
        self.comboBox_v1.setFont(font)
        self.comboBox_v1.setObjectName("comboBox_v1")
        self.comboBox_v1.addItem("")
        self.comboBox_v1.addItem("")
        self.comboBox_v1.addItem("")
        self.comboBox_v1.addItem("")
        self.comboBox_v1.addItem("")
        self.comboBox_v1.addItem("")
        self.lineEdit_v2 = QtWidgets.QLineEdit(metric_change)
        self.lineEdit_v2.setGeometry(QtCore.QRect(260, 160, 100, 20))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.lineEdit_v2.setFont(font)
        self.lineEdit_v2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_v2.setReadOnly(True)
        self.lineEdit_v2.setObjectName("lineEdit_v2")
        self.lineEdit_v1 = QtWidgets.QLineEdit(metric_change)
        self.lineEdit_v1.setGeometry(QtCore.QRect(40, 160, 100, 20))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.lineEdit_v1.setFont(font)
        self.lineEdit_v1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_v1.setObjectName("lineEdit_v1")
        self.comboBox_m1 = QtWidgets.QComboBox(metric_change)
        self.comboBox_m1.setGeometry(QtCore.QRect(140, 240, 50, 20))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(14)
        self.comboBox_m1.setFont(font)
        self.comboBox_m1.setObjectName("comboBox_m1")
        self.comboBox_m1.addItem("")
        self.comboBox_m1.addItem("")
        self.comboBox_m1.addItem("")
        self.comboBox_m1.addItem("")
        self.comboBox_m1.addItem("")
        self.comboBox_m1.addItem("")
        self.lineEdit_m1 = QtWidgets.QLineEdit(metric_change)
        self.lineEdit_m1.setGeometry(QtCore.QRect(40, 240, 100, 20))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.lineEdit_m1.setFont(font)
        self.lineEdit_m1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_m1.setObjectName("lineEdit_m1")
        self.pushButton_m = QtWidgets.QPushButton(metric_change)
        self.pushButton_m.setGeometry(QtCore.QRect(200, 240, 50, 20))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(18)
        self.pushButton_m.setFont(font)
        self.pushButton_m.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: 4px double ;")
        self.pushButton_m.setObjectName("pushButton_m")
        self.lineEdit_m2 = QtWidgets.QLineEdit(metric_change)
        self.lineEdit_m2.setGeometry(QtCore.QRect(260, 240, 100, 20))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.lineEdit_m2.setFont(font)
        self.lineEdit_m2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_m2.setReadOnly(True)
        self.lineEdit_m2.setObjectName("lineEdit_m2")
        self.comboBox_l2 = QtWidgets.QComboBox(metric_change)
        self.comboBox_l2.setGeometry(QtCore.QRect(360, 80, 50, 20))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(14)
        self.comboBox_l2.setFont(font)
        self.comboBox_l2.setObjectName("comboBox_l2")
        self.comboBox_l2.addItem("")
        self.comboBox_l2.addItem("")
        self.comboBox_l2.addItem("")
        self.comboBox_l2.addItem("")
        self.comboBox_l2.addItem("")
        self.comboBox_l2.addItem("")
        self.comboBox_l2.addItem("")
        self.comboBox_l2.addItem("")
        self.comboBox_l2.addItem("")
        self.comboBox_l2.addItem("")
        self.comboBox_l2.addItem("")
        self.comboBox_l2.addItem("")
        self.comboBox_l2.addItem("")
        self.comboBox_v2 = QtWidgets.QComboBox(metric_change)
        self.comboBox_v2.setGeometry(QtCore.QRect(360, 160, 50, 20))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(14)
        self.comboBox_v2.setFont(font)
        self.comboBox_v2.setObjectName("comboBox_v2")
        self.comboBox_v2.addItem("")
        self.comboBox_v2.addItem("")
        self.comboBox_v2.addItem("")
        self.comboBox_v2.addItem("")
        self.comboBox_v2.addItem("")
        self.comboBox_v2.addItem("")
        self.comboBox_m2 = QtWidgets.QComboBox(metric_change)
        self.comboBox_m2.setGeometry(QtCore.QRect(360, 240, 50, 20))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(14)
        self.comboBox_m2.setFont(font)
        self.comboBox_m2.setObjectName("comboBox_m2")
        self.comboBox_m2.addItem("")
        self.comboBox_m2.addItem("")
        self.comboBox_m2.addItem("")
        self.comboBox_m2.addItem("")
        self.comboBox_m2.addItem("")
        self.comboBox_m2.addItem("")
        self.listView = QtWidgets.QListView(metric_change)
        self.listView.setGeometry(QtCore.QRect(0, 0, 451, 301))
        self.listView.setStyleSheet("border-image: url(:/newPrefix/background2.jpg);")
        self.listView.setObjectName("listView")
        self.listView.raise_()
        self.lineEdit_l1.raise_()
        self.lineEdit_l2.raise_()
        self.comboBox_l1.raise_()
        self.label.raise_()
        self.label_l.raise_()
        self.label_v.raise_()
        self.label_m.raise_()
        self.pushButton_l.raise_()
        self.pushButton_v.raise_()
        self.comboBox_v1.raise_()
        self.lineEdit_v2.raise_()
        self.lineEdit_v1.raise_()
        self.comboBox_m1.raise_()
        self.lineEdit_m1.raise_()
        self.pushButton_m.raise_()
        self.lineEdit_m2.raise_()
        self.comboBox_l2.raise_()
        self.comboBox_v2.raise_()
        self.comboBox_m2.raise_()

        self.retranslateUi(metric_change)
        QtCore.QMetaObject.connectSlotsByName(metric_change)

    def retranslateUi(self, metric_change):
        _translate = QtCore.QCoreApplication.translate
        metric_change.setWindowTitle(_translate("metric_change", "度量转换"))
        self.comboBox_l1.setItemText(0, _translate("metric_change", "m"))
        self.comboBox_l1.setItemText(1, _translate("metric_change", "mm"))
        self.comboBox_l1.setItemText(2, _translate("metric_change", "cm"))
        self.comboBox_l1.setItemText(3, _translate("metric_change", "dm"))
        self.comboBox_l1.setItemText(4, _translate("metric_change", "km"))
        self.comboBox_l1.setItemText(5, _translate("metric_change", "寸"))
        self.comboBox_l1.setItemText(6, _translate("metric_change", "尺"))
        self.comboBox_l1.setItemText(7, _translate("metric_change", "丈"))
        self.comboBox_l1.setItemText(8, _translate("metric_change", "里"))
        self.comboBox_l1.setItemText(9, _translate("metric_change", "英寸"))
        self.comboBox_l1.setItemText(10, _translate("metric_change", "英尺"))
        self.comboBox_l1.setItemText(11, _translate("metric_change", "码"))
        self.comboBox_l1.setItemText(12, _translate("metric_change", "英里"))
        self.label.setText(_translate("metric_change", "先在下拉菜单中选好需要转换的单位，在左边的框中输入数据，点击等号进行转换"))
        self.label_l.setText(_translate("metric_change", "长度"))
        self.label_v.setText(_translate("metric_change", "体积"))
        self.label_m.setText(_translate("metric_change", "质量"))
        self.pushButton_l.setText(_translate("metric_change", "="))
        self.pushButton_v.setText(_translate("metric_change", "="))
        self.comboBox_v1.setItemText(0, _translate("metric_change", "L"))
        self.comboBox_v1.setItemText(1, _translate("metric_change", "mL"))
        self.comboBox_v1.setItemText(2, _translate("metric_change", "立方米"))
        self.comboBox_v1.setItemText(3, _translate("metric_change", "品脱"))
        self.comboBox_v1.setItemText(4, _translate("metric_change", "夸脱"))
        self.comboBox_v1.setItemText(5, _translate("metric_change", "加仑"))
        self.comboBox_m1.setItemText(0, _translate("metric_change", "g"))
        self.comboBox_m1.setItemText(1, _translate("metric_change", "mg"))
        self.comboBox_m1.setItemText(2, _translate("metric_change", "kg"))
        self.comboBox_m1.setItemText(3, _translate("metric_change", "吨"))
        self.comboBox_m1.setItemText(4, _translate("metric_change", "磅"))
        self.comboBox_m1.setItemText(5, _translate("metric_change", "盎司"))
        self.pushButton_m.setText(_translate("metric_change", "="))
        self.comboBox_l2.setItemText(0, _translate("metric_change", "m"))
        self.comboBox_l2.setItemText(1, _translate("metric_change", "mm"))
        self.comboBox_l2.setItemText(2, _translate("metric_change", "cm"))
        self.comboBox_l2.setItemText(3, _translate("metric_change", "dm"))
        self.comboBox_l2.setItemText(4, _translate("metric_change", "km"))
        self.comboBox_l2.setItemText(5, _translate("metric_change", "寸"))
        self.comboBox_l2.setItemText(6, _translate("metric_change", "尺"))
        self.comboBox_l2.setItemText(7, _translate("metric_change", "丈"))
        self.comboBox_l2.setItemText(8, _translate("metric_change", "里"))
        self.comboBox_l2.setItemText(9, _translate("metric_change", "英寸"))
        self.comboBox_l2.setItemText(10, _translate("metric_change", "英尺"))
        self.comboBox_l2.setItemText(11, _translate("metric_change", "码"))
        self.comboBox_l2.setItemText(12, _translate("metric_change", "英里"))
        self.comboBox_v2.setItemText(0, _translate("metric_change", "L"))
        self.comboBox_v2.setItemText(1, _translate("metric_change", "mL"))
        self.comboBox_v2.setItemText(2, _translate("metric_change", "立方米"))
        self.comboBox_v2.setItemText(3, _translate("metric_change", "品脱"))
        self.comboBox_v2.setItemText(4, _translate("metric_change", "夸脱"))
        self.comboBox_v2.setItemText(5, _translate("metric_change", "加仑"))
        self.comboBox_m2.setItemText(0, _translate("metric_change", "g"))
        self.comboBox_m2.setItemText(1, _translate("metric_change", "mg"))
        self.comboBox_m2.setItemText(2, _translate("metric_change", "kg"))
        self.comboBox_m2.setItemText(3, _translate("metric_change", "吨"))
        self.comboBox_m2.setItemText(4, _translate("metric_change", "磅"))
        self.comboBox_m2.setItemText(5, _translate("metric_change", "盎司"))

