# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'radix_change_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_radix_change(object):
    def setupUi(self, radix_change):
        radix_change.setObjectName("radix_change")
        radix_change.resize(325, 360)
        font = QtGui.QFont()
        font.setPointSize(9)
        radix_change.setFont(font)
        self.pushButton_0 = QtWidgets.QPushButton(radix_change)
        self.pushButton_0.setGeometry(QtCore.QRect(6, 310, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: 1px solid ;")
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_1 = QtWidgets.QPushButton(radix_change)
        self.pushButton_1.setGeometry(QtCore.QRect(6, 258, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: 1px solid ;")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(radix_change)
        self.pushButton_2.setGeometry(QtCore.QRect(66, 258, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: 1px solid ;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(radix_change)
        self.pushButton_3.setGeometry(QtCore.QRect(126, 258, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: 1px solid ;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_a = QtWidgets.QPushButton(radix_change)
        self.pushButton_a.setGeometry(QtCore.QRect(66, 310, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_a.setFont(font)
        self.pushButton_a.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: 1px solid ;")
        self.pushButton_a.setObjectName("pushButton_a")
        self.pushButton_b = QtWidgets.QPushButton(radix_change)
        self.pushButton_b.setGeometry(QtCore.QRect(126, 310, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_b.setFont(font)
        self.pushButton_b.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: 1px solid ;")
        self.pushButton_b.setObjectName("pushButton_b")
        self.pushButton_c = QtWidgets.QPushButton(radix_change)
        self.pushButton_c.setGeometry(QtCore.QRect(186, 310, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_c.setFont(font)
        self.pushButton_c.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: 1px solid ;")
        self.pushButton_c.setObjectName("pushButton_c")
        self.pushButton_4 = QtWidgets.QPushButton(radix_change)
        self.pushButton_4.setGeometry(QtCore.QRect(6, 206, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: 1px solid ;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(radix_change)
        self.pushButton_5.setGeometry(QtCore.QRect(66, 206, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: 1px solid ;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(radix_change)
        self.pushButton_6.setGeometry(QtCore.QRect(126, 206, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: 1px solid ;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(radix_change)
        self.pushButton_7.setGeometry(QtCore.QRect(6, 154, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: 1px solid ;")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(radix_change)
        self.pushButton_8.setGeometry(QtCore.QRect(66, 154, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: 1px solid ;")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(radix_change)
        self.pushButton_9.setGeometry(QtCore.QRect(126, 154, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: 1px solid ;")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_d = QtWidgets.QPushButton(radix_change)
        self.pushButton_d.setGeometry(QtCore.QRect(186, 258, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_d.setFont(font)
        self.pushButton_d.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: 1px solid ;")
        self.pushButton_d.setObjectName("pushButton_d")
        self.pushButton_e = QtWidgets.QPushButton(radix_change)
        self.pushButton_e.setGeometry(QtCore.QRect(186, 206, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_e.setFont(font)
        self.pushButton_e.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: 1px solid ;")
        self.pushButton_e.setObjectName("pushButton_e")
        self.pushButton_f = QtWidgets.QPushButton(radix_change)
        self.pushButton_f.setGeometry(QtCore.QRect(186, 154, 56, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(24)
        self.pushButton_f.setFont(font)
        self.pushButton_f.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: 1px solid ;")
        self.pushButton_f.setObjectName("pushButton_f")
        self.pushButton_bin = QtWidgets.QPushButton(radix_change)
        self.pushButton_bin.setGeometry(QtCore.QRect(246, 310, 71, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(20)
        self.pushButton_bin.setFont(font)
        self.pushButton_bin.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"border: 4px double ;")
        self.pushButton_bin.setObjectName("pushButton_bin")
        self.pushButton_oct = QtWidgets.QPushButton(radix_change)
        self.pushButton_oct.setGeometry(QtCore.QRect(246, 258, 71, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(20)
        self.pushButton_oct.setFont(font)
        self.pushButton_oct.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"border: 4px double ;")
        self.pushButton_oct.setObjectName("pushButton_oct")
        self.pushButton_dec = QtWidgets.QPushButton(radix_change)
        self.pushButton_dec.setGeometry(QtCore.QRect(246, 206, 71, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(20)
        self.pushButton_dec.setFont(font)
        self.pushButton_dec.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"border: 4px double ;")
        self.pushButton_dec.setObjectName("pushButton_dec")
        self.pushButton_hex = QtWidgets.QPushButton(radix_change)
        self.pushButton_hex.setGeometry(QtCore.QRect(246, 154, 71, 41))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(20)
        self.pushButton_hex.setFont(font)
        self.pushButton_hex.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"border: 4px double ;")
        self.pushButton_hex.setObjectName("pushButton_hex")
        self.lineEdit = QtWidgets.QLineEdit(radix_change)
        self.lineEdit.setGeometry(QtCore.QRect(66, 120, 251, 30))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(20)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_bin = QtWidgets.QLineEdit(radix_change)
        self.lineEdit_bin.setGeometry(QtCore.QRect(66, 90, 251, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        self.lineEdit_bin.setFont(font)
        self.lineEdit_bin.setText("")
        self.lineEdit_bin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_bin.setReadOnly(True)
        self.lineEdit_bin.setObjectName("lineEdit_bin")
        self.lineEdit_oct = QtWidgets.QLineEdit(radix_change)
        self.lineEdit_oct.setGeometry(QtCore.QRect(66, 60, 251, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        self.lineEdit_oct.setFont(font)
        self.lineEdit_oct.setText("")
        self.lineEdit_oct.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_oct.setReadOnly(True)
        self.lineEdit_oct.setObjectName("lineEdit_oct")
        self.lineEdit_hex = QtWidgets.QLineEdit(radix_change)
        self.lineEdit_hex.setGeometry(QtCore.QRect(66, 0, 251, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        self.lineEdit_hex.setFont(font)
        self.lineEdit_hex.setText("")
        self.lineEdit_hex.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_hex.setReadOnly(True)
        self.lineEdit_hex.setObjectName("lineEdit_hex")
        self.lineEdit_dec = QtWidgets.QLineEdit(radix_change)
        self.lineEdit_dec.setGeometry(QtCore.QRect(66, 30, 251, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        self.lineEdit_dec.setFont(font)
        self.lineEdit_dec.setText("")
        self.lineEdit_dec.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_dec.setReadOnly(True)
        self.lineEdit_dec.setObjectName("lineEdit_dec")
        self.label_hex = QtWidgets.QLabel(radix_change)
        self.label_hex.setGeometry(QtCore.QRect(0, 0, 71, 30))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(18)
        self.label_hex.setFont(font)
        self.label_hex.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hex.setObjectName("label_hex")
        self.label_dec = QtWidgets.QLabel(radix_change)
        self.label_dec.setGeometry(QtCore.QRect(0, 30, 71, 30))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(18)
        self.label_dec.setFont(font)
        self.label_dec.setAlignment(QtCore.Qt.AlignCenter)
        self.label_dec.setObjectName("label_dec")
        self.label_oct = QtWidgets.QLabel(radix_change)
        self.label_oct.setGeometry(QtCore.QRect(0, 60, 71, 30))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(18)
        self.label_oct.setFont(font)
        self.label_oct.setAlignment(QtCore.Qt.AlignCenter)
        self.label_oct.setObjectName("label_oct")
        self.label_bin = QtWidgets.QLabel(radix_change)
        self.label_bin.setGeometry(QtCore.QRect(0, 90, 71, 30))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(18)
        self.label_bin.setFont(font)
        self.label_bin.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bin.setObjectName("label_bin")
        self.pushButton_ce = QtWidgets.QPushButton(radix_change)
        self.pushButton_ce.setGeometry(QtCore.QRect(6, 120, 56, 30))
        font = QtGui.QFont()
        font.setFamily("汉仪铸字木头人W")
        font.setPointSize(18)
        self.pushButton_ce.setFont(font)
        self.pushButton_ce.setStyleSheet("background-color: rgb(255, 85, 85);\n"
"border: 4px double ;")
        self.pushButton_ce.setObjectName("pushButton_ce")
        self.listWidget = QtWidgets.QListWidget(radix_change)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 331, 361))
        self.listWidget.setStyleSheet("border-image: url(:/newPrefix/background2.jpg);")
        self.listWidget.setObjectName("listWidget")
        self.listWidget.raise_()
        self.pushButton_0.raise_()
        self.pushButton_1.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_a.raise_()
        self.pushButton_b.raise_()
        self.pushButton_c.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.pushButton_9.raise_()
        self.pushButton_d.raise_()
        self.pushButton_e.raise_()
        self.pushButton_f.raise_()
        self.pushButton_bin.raise_()
        self.pushButton_oct.raise_()
        self.pushButton_dec.raise_()
        self.pushButton_hex.raise_()
        self.lineEdit.raise_()
        self.lineEdit_bin.raise_()
        self.lineEdit_oct.raise_()
        self.lineEdit_hex.raise_()
        self.lineEdit_dec.raise_()
        self.label_hex.raise_()
        self.label_dec.raise_()
        self.label_oct.raise_()
        self.label_bin.raise_()
        self.pushButton_ce.raise_()

        self.retranslateUi(radix_change)
        QtCore.QMetaObject.connectSlotsByName(radix_change)

    def retranslateUi(self, radix_change):
        _translate = QtCore.QCoreApplication.translate
        radix_change.setWindowTitle(_translate("radix_change", "进制转换"))
        self.pushButton_0.setText(_translate("radix_change", "0"))
        self.pushButton_1.setText(_translate("radix_change", "1"))
        self.pushButton_2.setText(_translate("radix_change", "2"))
        self.pushButton_3.setText(_translate("radix_change", "3"))
        self.pushButton_a.setText(_translate("radix_change", "A"))
        self.pushButton_b.setText(_translate("radix_change", "B"))
        self.pushButton_c.setText(_translate("radix_change", "C"))
        self.pushButton_4.setText(_translate("radix_change", "4"))
        self.pushButton_5.setText(_translate("radix_change", "5"))
        self.pushButton_6.setText(_translate("radix_change", "6"))
        self.pushButton_7.setText(_translate("radix_change", "7"))
        self.pushButton_8.setText(_translate("radix_change", "8"))
        self.pushButton_9.setText(_translate("radix_change", "9"))
        self.pushButton_d.setText(_translate("radix_change", "D"))
        self.pushButton_e.setText(_translate("radix_change", "E"))
        self.pushButton_f.setText(_translate("radix_change", "F"))
        self.pushButton_bin.setText(_translate("radix_change", "BIN"))
        self.pushButton_oct.setText(_translate("radix_change", "OCT"))
        self.pushButton_dec.setText(_translate("radix_change", "DEC"))
        self.pushButton_hex.setText(_translate("radix_change", "HEX"))
        self.label_hex.setText(_translate("radix_change", "HEX"))
        self.label_dec.setText(_translate("radix_change", "DEC"))
        self.label_oct.setText(_translate("radix_change", "OCT"))
        self.label_bin.setText(_translate("radix_change", "BIN"))
        self.pushButton_ce.setText(_translate("radix_change", "CE"))

